apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp-operator
  template:
    metadata:
      labels:
        name: webapp-operator
    spec:
      serviceAccountName: webapp-operator
      containers:
        - name: webapp-operator
          # Replace this with the built image name
          image: lholler/webapp-operator:v0.0.2
          command:
          - webapp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "webapp-operator"
